### ISSUE TITLE
Little error in equation (2), (3)

### ISSUE THREAD

**Issue by zzowenzz** [wdzhao123/MetaFusion#4]
Hi, I think you miss the $\prime$ symbol in equation (2) and (3), which is represented as the parameter optimization for $MFG$ and $FT$ module.

**Comment by ccy2248** [comment]
> Hi, I think you miss the ′ symbol in equation (2) and (3), which is represented as the parameter optimization for M F G and F T module.

bro this paper is a wholly shit and i don't think that it's truly work as well as paper says,specially the equation(4)and(5) does not make sense at least，because it miss the βF‘ in equation(1) deliberately.Unless the author assumes the learning rate is 1 or admits that his paper is a piece of shit

**Comment by zzowenzz** [comment]
While, I guess there will be no further reponse from the author since it is already 9 months past.
